name: Compare functions
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          CONTAINS_FUNC: ${{ containts('Hello', 'ell') }}
          STARTS_WITH_FUNC: ${{ With('Hello', 'He') }}
          ENDS_WITH_FUNC: ${{ With('Hello', 'lo') }}
        